/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Hattmakarna;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author rilam
 */
public class HanteraMaterial extends javax.swing.JFrame {
private InfDB idb;
    /**
     * Creates new form HanteraMaterial
     */
    public HanteraMaterial(InfDB idb) {
        initComponents();
        this.idb = idb;
        fillComboboxMaterialNamn();
        kontrolleraLagerMangd();
        kontrolleraEnhetspris();
        kontrolleraMangd();
        this.setLocationRelativeTo(null);
        HanteraMaterial.this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLMaterialMangd = new javax.swing.JLabel();
        jTAndraEnhetspris = new javax.swing.JTextField();
        jLValjMaterial = new javax.swing.JLabel();
        jCMaterialNamn = new javax.swing.JComboBox<>();
        jBAndra = new javax.swing.JButton();
        jLRubrik = new javax.swing.JLabel();
        jLFyllPa = new javax.swing.JLabel();
        jLValj2 = new javax.swing.JLabel();
        jCMaterialNamnet = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jTLagerMangd = new javax.swing.JTextField();
        jBFyllPa = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLAndraInformation = new javax.swing.JLabel();
        jLMaterial = new javax.swing.JLabel();
        jLAndraNamn = new javax.swing.JLabel();
        jCMaterialNamnen = new javax.swing.JComboBox<>();
        jLAndraEnhetspris = new javax.swing.JLabel();
        jTAndraNamn = new javax.swing.JTextField();
        jBAndraInformation = new javax.swing.JButton();
        jLFyllI = new javax.swing.JLabel();
        jLAndraMangd = new javax.swing.JLabel();
        jTAndraMangd = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(249, 248, 244));

        jLMaterialMangd.setFont(new java.awt.Font("Futura", 0, 17)); // NOI18N
        jLMaterialMangd.setText("Sätt materialmängd till 0 i lager");

        jTAndraEnhetspris.setFont(new java.awt.Font("Futura", 0, 14)); // NOI18N

        jLValjMaterial.setFont(new java.awt.Font("Futura", 0, 14)); // NOI18N
        jLValjMaterial.setText("Välj material:");

        jCMaterialNamn.setFont(new java.awt.Font("Futura", 0, 14)); // NOI18N
        jCMaterialNamn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jBAndra.setFont(new java.awt.Font("Futura", 0, 14)); // NOI18N
        jBAndra.setText("Ändra");
        jBAndra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAndraActionPerformed(evt);
            }
        });

        jLRubrik.setFont(new java.awt.Font("Futura", 0, 30)); // NOI18N
        jLRubrik.setText("Hantera material");

        jLFyllPa.setFont(new java.awt.Font("Futura", 0, 17)); // NOI18N
        jLFyllPa.setText("Fyll på befintligt material");

        jLValj2.setFont(new java.awt.Font("Futura", 0, 14)); // NOI18N
        jLValj2.setText("Välj material:");

        jCMaterialNamnet.setFont(new java.awt.Font("Futura", 0, 14)); // NOI18N
        jCMaterialNamnet.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setFont(new java.awt.Font("Futura", 0, 14)); // NOI18N
        jLabel3.setText("Skriv mängd:");

        jTLagerMangd.setFont(new java.awt.Font("Futura", 0, 14)); // NOI18N

        jBFyllPa.setFont(new java.awt.Font("Futura", 0, 14)); // NOI18N
        jBFyllPa.setText("Fyll på lagersaldo");
        jBFyllPa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBFyllPaActionPerformed(evt);
            }
        });

        jLAndraInformation.setFont(new java.awt.Font("Futura", 0, 17)); // NOI18N
        jLAndraInformation.setText("Ändra information om material");

        jLMaterial.setFont(new java.awt.Font("Futura", 0, 14)); // NOI18N
        jLMaterial.setText("Välj material:");

        jLAndraNamn.setFont(new java.awt.Font("Futura", 0, 14)); // NOI18N
        jLAndraNamn.setText("Ändra namn:");

        jCMaterialNamnen.setFont(new java.awt.Font("Futura", 0, 14)); // NOI18N
        jCMaterialNamnen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLAndraEnhetspris.setFont(new java.awt.Font("Futura", 0, 14)); // NOI18N
        jLAndraEnhetspris.setText("Ändra enhetspris:");

        jTAndraNamn.setFont(new java.awt.Font("Futura", 0, 14)); // NOI18N

        jBAndraInformation.setFont(new java.awt.Font("Futura", 0, 14)); // NOI18N
        jBAndraInformation.setText("Ändra information");
        jBAndraInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAndraInformationActionPerformed(evt);
            }
        });

        jLFyllI.setFont(new java.awt.Font("Futura", 0, 14)); // NOI18N
        jLFyllI.setText("Fyll i vilken information som ska ändras:");

        jLAndraMangd.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLAndraMangd.setText("Ändra Mängd:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLMaterialMangd)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLValjMaterial)
                        .addGap(87, 87, 87)
                        .addComponent(jCMaterialNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBAndra, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLFyllPa)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLValj2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(62, 62, 62)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jCMaterialNamnet, 0, 182, Short.MAX_VALUE)
                            .addComponent(jTLagerMangd))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBFyllPa, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLRubrik)
                        .addGap(202, 202, 202))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLAndraNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLFyllI, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBAndraInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jCMaterialNamnen, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLAndraInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLAndraEnhetspris, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLAndraMangd, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(41, 41, 41)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTAndraNamn, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                                        .addComponent(jTAndraEnhetspris)
                                        .addComponent(jTAndraMangd))
                                    .addGap(0, 0, Short.MAX_VALUE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLRubrik, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLMaterialMangd)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLValjMaterial)
                    .addComponent(jCMaterialNamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBAndra, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLFyllPa, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCMaterialNamnet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLValj2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTLagerMangd, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jBFyllPa, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLAndraInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLMaterial))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jCMaterialNamnen, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLFyllI)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLAndraNamn)
                            .addComponent(jTAndraNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jBAndraInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLAndraEnhetspris))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jTAndraEnhetspris, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTAndraMangd, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLAndraMangd))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBAndraInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAndraInformationActionPerformed
        

            String materialNamn = jCMaterialNamnen.getSelectedItem().toString();
            String nyttNamn = jTAndraNamn.getText();
            String nyttEnhetspris = jTAndraEnhetspris.getText();
            String nyMangd = jTAndraMangd.getText();
            String materialID = ("");

            try {
                materialID = idb.fetchSingle("SELECT MaterialID from Material WHERE Materialnamn = '"+ materialNamn + "'");

                if(ValideringsKlass.rutaEmpty(jTAndraNamn)){
                    System.out.println("Namnet har inte ändrats");
                }

                else{
                    idb.update("UPDATE material SET Materialnamn = '"+nyttNamn+"' WHERE MaterialID = '"+ materialID +"'");
                    JOptionPane.showMessageDialog(null, "Namnet har ändrats till "+nyttNamn+"!");
                }

                if(ValideringsKlass.rutaEmpty(jTAndraEnhetspris)){
                    System.out.println("Enhetspriset har inte ändrats");
                }

                else  {
                    idb.update("UPDATE material SET Enhetspris = '"+nyttEnhetspris+"' WHERE MaterialID = '"+ materialID +"'");
                    JOptionPane.showMessageDialog(null, "Enhetspriset har ändrats till "+nyttEnhetspris+"!");
                }
                
                if(ValideringsKlass.rutaEmpty(jTAndraMangd)){
                    System.out.println("Mängd har inte ändrats");
                }
                else {
                     idb.update("UPDATE antalvara SET Antal = '"+ nyMangd +"' WHERE MaterialID = '"+ materialID +"'");
                     idb.update("UPDATE kvadratmetervara SET Kvadratmeter =  '"+ nyMangd +"' WHERE MaterialID = '"+ materialID +"'");
                     idb.update("UPDATE metervara SET Meter =  '"+ nyMangd +"' WHERE MaterialID = '"+ materialID +"'");
                     JOptionPane.showMessageDialog(null, "Mängden har ändrats till "+nyMangd+ "!");
                }

            } catch (InfException ex) {
                Logger.getLogger(HanteraMaterial.class.getName()).log(Level.SEVERE, null, ex);
            }

        
        
        
        
        
    }//GEN-LAST:event_jBAndraInformationActionPerformed

    private void jBFyllPaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBFyllPaActionPerformed
        if(ValideringsKlass.textFaltHarVarde2(jTLagerMangd)){
       

                ArrayList<String> sqlfraga1 = new ArrayList<String>();
                ArrayList<String> sqlfraga2 = new ArrayList<String>();
                ArrayList<String> sqlfraga3 = new ArrayList<String>();
                String materialNamn = jCMaterialNamnet.getSelectedItem().toString();
                String mangd = jTLagerMangd.getText();
                String materialID = ("");

                try{

                    materialID = idb.fetchSingle("SELECT MaterialID from Material WHERE Materialnamn = '"+ materialNamn + "'");
                    String fraga1 = idb.fetchSingle("SELECT Antal FROM antalvara WHERE MaterialID = '"+ materialID +"'");
                    String fraga2 = idb.fetchSingle("SELECT Kvadratmeter FROM kvadratmetervara WHERE MaterialID = '"+ materialID +"'");
                    String fraga3 = idb.fetchSingle("SELECT Meter FROM metervara WHERE MaterialID = '"+ materialID +"'");
                    sqlfraga1 = idb.fetchColumn("SELECT MaterialID FROM antalvara");
                    sqlfraga2 = idb.fetchColumn("SELECT MaterialID FROM kvadratmetervara");
                    sqlfraga3 = idb.fetchColumn("SELECT MaterialID FROM metervara");

                    for(String antal1: sqlfraga1) {
                        if(materialID.equals(antal1))
                        {
                           
                            idb.update("UPDATE antalvara SET Antal = '"+mangd+"' + '"+fraga1+"' WHERE MaterialID = '"+ materialID +"'");
                            String nymangd1 = idb.fetchSingle("SELECT Antal FROM antalvara WHERE MaterialID = '"+ materialID +"'");
                            JOptionPane.showMessageDialog(null, "Nytt saldo är "+nymangd1+"");
                        }

                    }

                    for(String antal2: sqlfraga2) {
                        if(materialID.equals(antal2))
                        {
                           
                            idb.update("UPDATE kvadratmetervara SET Kvadratmeter = '"+mangd+"' + '"+fraga2+"' WHERE MaterialID = '"+ materialID +"'");
                            String nymangd2 = idb.fetchSingle("SELECT kvadratmeter FROM Kvadratmetervara WHERE MaterialID = '"+ materialID +"'");
                            JOptionPane.showMessageDialog(null, "Nytt saldo är "+nymangd2+"");
                        }
                    }

                    for(String antal3: sqlfraga3) {
                        if(materialID.equals(antal3))
                        {
                            
                            idb.update("UPDATE metervara SET Meter = '"+mangd+"' + '"+fraga3+"' WHERE MaterialID = '"+ materialID +"'");
                            String nymangd3 = idb.fetchSingle("SELECT Meter FROM metervara WHERE MaterialID = '"+ materialID +"'");
                            JOptionPane.showMessageDialog(null, "Nytt saldo är "+nymangd3+"");
                        }
                    }

                }
                catch(InfException ex){
                    Logger.getLogger(HanteraMaterial.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        
        
        
    }//GEN-LAST:event_jBFyllPaActionPerformed

    private void jBAndraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAndraActionPerformed
        // TODO add your handling code here:
        String materialNamn = jCMaterialNamn.getSelectedItem().toString();
        String materialID = ("");
        try{
            materialID = idb.fetchSingle("SELECT MaterialID from Material WHERE Materialnamn = '"+ materialNamn + "'");

            idb.update("UPDATE antalvara SET Antal = 0 WHERE MaterialID = '"+ materialID +"'");
            idb.update("UPDATE kvadratmetervara SET Kvadratmeter = 0 WHERE MaterialID = '"+ materialID +"'");
            idb.update("UPDATE metervara SET Meter = 0 WHERE MaterialID = '"+ materialID +"'");

            JOptionPane.showMessageDialog(null, "Nu har lagersaldot ändrats till 0");
        }
        catch(InfException ex){
            Logger.getLogger(HanteraMaterial.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jBAndraActionPerformed

    private void fillComboboxMaterialNamn(){ 
    jCMaterialNamn.removeAllItems();
    jCMaterialNamnet.removeAllItems();
    jCMaterialNamnen.removeAllItems();
    String fraga = "SELECT MaterialNamn FROM Material";
    
    ArrayList<String> MaterialNamnLista = new ArrayList<String>();
    try {
    MaterialNamnLista= idb.fetchColumn(fraga);
    
    for(String material: MaterialNamnLista)
    {
      jCMaterialNamn.addItem(material);
      jCMaterialNamnet.addItem(material);
      jCMaterialNamnen.addItem(material);
    }
    }   catch (InfException ex){
        Logger.getLogger(HanteraMaterial.class.getName()).log(Level.SEVERE, null, ex);
        }
    } 
    
       private void kontrolleraLagerMangd() {
        jTLagerMangd.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                ValideringsKlass.endastNummerTillåten2(jTLagerMangd);
                ValideringsKlass.endastPunkt(jTLagerMangd);
                ValideringsKlass.endastPositivt(jTLagerMangd);
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                ValideringsKlass.endastNummerTillåten2(jTLagerMangd);
                ValideringsKlass.endastPunkt(jTLagerMangd);
                ValideringsKlass.endastPositivt(jTLagerMangd);
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                ValideringsKlass.endastNummerTillåten2(jTLagerMangd);
                ValideringsKlass.endastPunkt(jTLagerMangd);
                ValideringsKlass.endastPositivt(jTLagerMangd);
            }
        });
      }

  private void kontrolleraEnhetspris() {
        jTAndraEnhetspris.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                ValideringsKlass.endastNummerTillåten3(jTAndraEnhetspris);
                ValideringsKlass.endastPositivt(jTAndraEnhetspris);
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                ValideringsKlass.endastNummerTillåten3(jTAndraEnhetspris);
                ValideringsKlass.endastPositivt(jTAndraEnhetspris);
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                ValideringsKlass.endastNummerTillåten3(jTAndraEnhetspris);
                ValideringsKlass.endastPositivt(jTAndraEnhetspris);
            }
        });
    }
  
    private void kontrolleraMangd() {
        jTAndraMangd.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                ValideringsKlass.endastNummerTillåten2(jTAndraMangd);
                ValideringsKlass.endastPunkt(jTAndraMangd);
                ValideringsKlass.endastPositivt(jTAndraMangd);
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                ValideringsKlass.endastNummerTillåten2(jTAndraMangd);
                ValideringsKlass.endastPunkt(jTAndraMangd);
                ValideringsKlass.endastPositivt(jTAndraMangd);
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                ValideringsKlass.endastNummerTillåten2(jTAndraMangd);
                ValideringsKlass.endastPunkt(jTAndraMangd);
                ValideringsKlass.endastPositivt(jTAndraMangd);
            }
        });
    }
     
  
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAndra;
    private javax.swing.JButton jBAndraInformation;
    private javax.swing.JButton jBFyllPa;
    private javax.swing.JComboBox<String> jCMaterialNamn;
    private javax.swing.JComboBox<String> jCMaterialNamnen;
    private javax.swing.JComboBox<String> jCMaterialNamnet;
    private javax.swing.JLabel jLAndraEnhetspris;
    private javax.swing.JLabel jLAndraInformation;
    private javax.swing.JLabel jLAndraMangd;
    private javax.swing.JLabel jLAndraNamn;
    private javax.swing.JLabel jLFyllI;
    private javax.swing.JLabel jLFyllPa;
    private javax.swing.JLabel jLMaterial;
    private javax.swing.JLabel jLMaterialMangd;
    private javax.swing.JLabel jLRubrik;
    private javax.swing.JLabel jLValj2;
    private javax.swing.JLabel jLValjMaterial;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTAndraEnhetspris;
    private javax.swing.JTextField jTAndraMangd;
    private javax.swing.JTextField jTAndraNamn;
    private javax.swing.JTextField jTLagerMangd;
    // End of variables declaration//GEN-END:variables
}
